version: "2.4"

services:
  frontend:
    image: ghcr.io/lutoma/shortdiary/shortdiary-frontend:latest
    restart: unless-stopped
    pids_limit: 200
    ports:
      - 8009:80
    labels:
      - com.centurylinklabs.watchtower.enable=true

  api:
    image: ghcr.io/lutoma/shortdiary/shortdiary-api:latest
    restart: unless-stopped
    ports:
      - 8010:80
    labels:
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - data:/data

volumes:
  data:
